package Controller.User;
import Controller.Admin.Login_RegisterController;
import DAOImplement.ChungNhanKetHonDAOImpl;
import DAOImplement.LyHonDAOImpl;
import InterfaceDAO.IChungNhanKetHonDAO;
import InterfaceDAO.ILyHonDAO;
import Menu.MenuEvent;
import Models.ChungNhanKetHonModel;
import Models.LyHonModel;
import Models.ThongTinHoKhau;
import ServiceImplement.HoKhauServiceImpl;
import java.awt.Component;
import javax.swing.JOptionPane;


public class HomeControllerUser extends javax.swing.JFrame {

    public HomeControllerUser() {
        initComponents();
               
        IChungNhanKetHonDAO chungNhanKetHonDAO = new ChungNhanKetHonDAOImpl();
        String currentUser = Login_RegisterController.AppContext.userName;
        ChungNhanKetHonModel cnkh = chungNhanKetHonDAO.findOneCNKH(currentUser, currentUser);
         
        ChungNhanKetHonModel ketHon = chungNhanKetHonDAO.findOneCNKH_TrangThai(currentUser, currentUser);

        ILyHonDAO lyHonDAO = new LyHonDAOImpl();
        LyHonModel lyHon = lyHonDAO.findOneByMaCNKH(ketHon.getMaCnkh());
        
        ThongTinHoKhau hk = new HoKhauServiceImpl().findOneByCCCD(currentUser);
        showForm(new ThongTinCongDanControllerUser());
        menuUser.setMenuEvent(new MenuEvent() {
            @Override
            public void selected(int index, int subIndex) {
           
               if (index == 0) {
                    showForm(new ThongTinCongDanControllerUser());
                } else if (index == 1 && subIndex == 1) {
                    showForm(new ThongTinKhaiSinhControllerUser());
                } else if(index == 1 && subIndex == 2){
                    if(hk.getMaHoKhau()==null){
                        JOptionPane.showMessageDialog(null, "Công dân không có hộ khẩu!");
                        return;
                }
                    showForm(new ThongTinHoKhauControllerUser());
                } else if(index == 1 && subIndex == 3){
                    showForm(new TamTruControllerUser());
                } else if(index == 1 && subIndex == 4){
                    showForm(new TamVangControllerUser());
                } else if(index == 1 && subIndex == 5){
                    if(cnkh.getMaCnkh()==null){
                        JOptionPane.showMessageDialog(null, "Công dân chưa kết hôn");
                        return;
                    }
                    showForm(new GiayChungNhanKetHonControllerUser());
                } else if(index == 1 && subIndex == 6){
                    if(lyHon.getMaLh()==null){
                        JOptionPane.showMessageDialog(null, "Công dân chưa ly hôn");
                        return;
                    }
                    showForm(new GiayXacNhanLyHonControllerUser());
                } else if(index == 2){
                    showForm(new DanhGiaControllerUser());
                }
            }
        });
    }

    private void showForm(Component com) {
        panel.removeAll();
        panel.add(com);
        panel.repaint();
        panel.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPaneWin111 = new Swing.ScrollPaneWin11();
        menuUser = new Menu.MenuUser();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_logOutUser = new Swing.Button();
        panel = new Swing.PanelRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);

        scrollPaneWin111.setBackground(new java.awt.Color(255, 255, 255));
        scrollPaneWin111.setBorder(null);
        scrollPaneWin111.setViewportView(menuUser);

        header.setBackground(new java.awt.Color(21, 110, 71));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("THÔNG TIN CÔNG DÂN");

        btn_logOutUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logout-custom.png"))); // NOI18N
        btn_logOutUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logOutUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 816, Short.MAX_VALUE)
                .addComponent(btn_logOutUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_logOutUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scrollPaneWin111, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneWin111, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                    .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logOutUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logOutUserActionPerformed
        int confirmed = JOptionPane.showConfirmDialog(null,
                "Bạn có muốn đăng xuất khỏi tài khoản?", "Exit Program Confirmation",
                JOptionPane.YES_NO_OPTION);

        if (confirmed == JOptionPane.YES_OPTION) {
            Login_RegisterController lg = new Login_RegisterController();
            lg.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btn_logOutUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeControllerUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeControllerUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeControllerUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeControllerUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeControllerUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Swing.Button btn_logOutUser;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private Menu.MenuUser menuUser;
    private Swing.PanelRound panel;
    private Swing.ScrollPaneWin11 scrollPaneWin111;
    // End of variables declaration//GEN-END:variables
}
