package Controller.User;

import Controller.Admin.Login_RegisterController;
import DAOImplement.CongDanDAOImpl;
import InterfaceService.ICongDanService;
import InterfaceService.ITamTruServiceUser;
import Models.CongDanModel;
import Models.DonTamTruUser;
import ServiceImplement.CongDanServiceImpl;
import ServiceImplement.TamTruServiceImplUser;
import com.toedter.calendar.JDateChooser;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.text.ParseException;


public class TamTruControllerUser extends javax.swing.JPanel {

    
    DefaultTableModel model;
    List<DonTamTruUser> listTamTru;
    ITamTruServiceUser tamTruService = new TamTruServiceImplUser();
    ICongDanService CongDanService = new CongDanServiceImpl();
    CongDanModel cd = new CongDanModel();

    public TamTruControllerUser() {
        initComponents();
        model = (DefaultTableModel) tbl_thongTinTamTru.getModel();
        tbl_thongTinTamTru.fixTable(jScrollPane2);
        showInfo();

        showTable();
    }

    private void showTable() {
        model.setRowCount(0);
        listTamTru = tamTruService.findAllTT(Login_RegisterController.AppContext.userName);
        for (DonTamTruUser tamTru : listTamTru) {
            model.addRow(new Object[]{tamTru.getMaTT(), tamTru.getNgayDk(), tamTru.getNgayDen(), tamTru.getNgayDi(), tamTru.getHoTen(), tamTru.getNgaySinh(), tamTru.getGioiTinh(), tamTru.getCCCD(), tamTru.getNoiCap(), tamTru.getNgayCap(), tamTru.getLiDo(), tamTru.getSdt(), tamTru.getEmail(), tamTru.getNoiDangKy()});
        }
    }

    private void showInfo() {
        cd = new CongDanDAOImpl().findOneWithoutAdd(Login_RegisterController.AppContext.userName);
        tf_hoTen1.setText(cd.getHoTen());
        tf_soCCCD.setText(cd.getCCCD());
        jDateNgaySinh.setDate(cd.getNgaySinh());
        jDateNgayCap.setDate(cd.getNgcCccd());
        tf_noiCapCCCD.setText(cd.getNcCccd());
        tf_soDienThoai.setText(cd.getSDT());
        tf_email.setText(cd.getEmail());
        tf_gioiTinh.setText(cd.getGioiTinh());
        jDateNgayDangKy.setDate(new java.util.Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tf_gioiTinh = new Swing.TextField();
        tf_noiCapCCCD = new Swing.TextField();
        tf_soCCCD = new Swing.TextField();
        tf_email = new Swing.TextField();
        tf_maTamTru = new Swing.TextField();
        tf_soDienThoai = new Swing.TextField();
        btn_them = new Swing.Button();
        jLabel1 = new javax.swing.JLabel();
        btn_luu = new Swing.Button();
        tf_lyDo = new Swing.TextField();
        tf_noidangky = new Swing.TextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDateNgayCap = new com.toedter.calendar.JDateChooser();
        jDateNgaySinh = new com.toedter.calendar.JDateChooser();
        jDateNgayDangKy = new com.toedter.calendar.JDateChooser();
        jDateDen = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jDateNgayDi = new com.toedter.calendar.JDateChooser();
        btn_xoaDuLieu1 = new Swing.Button();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_thongTinTamTru = new Swing.TableDark();
        tf_hoTen1 = new Swing.TextField();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(920, 540));
        jPanel1.setPreferredSize(new java.awt.Dimension(920, 540));

        tf_gioiTinh.setEditable(false);
        tf_gioiTinh.setLabelText("Giới tính");

        tf_noiCapCCCD.setEditable(false);
        tf_noiCapCCCD.setLabelText("Nơi cấp CCCD");

        tf_soCCCD.setEditable(false);
        tf_soCCCD.setLabelText("Số CCCD");

        tf_email.setEditable(false);
        tf_email.setLabelText("Email");

        tf_maTamTru.setEditable(false);
        tf_maTamTru.setBackground(new java.awt.Color(255, 255, 255));
        tf_maTamTru.setLabelText("Mã tạm trú");

        tf_soDienThoai.setEditable(false);
        tf_soDienThoai.setLabelText("Số điện thoại");

        btn_them.setBackground(new java.awt.Color(18, 99, 63));
        btn_them.setForeground(new java.awt.Color(255, 255, 255));
        btn_them.setText("Đăng ký đơn");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("THÔNG TIN TẠM TRÚ");

        btn_luu.setBackground(new java.awt.Color(18, 99, 63));
        btn_luu.setForeground(new java.awt.Color(255, 255, 255));
        btn_luu.setText("Lưu");
        btn_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luuActionPerformed(evt);
            }
        });

        tf_lyDo.setLabelText("Lý do");

        tf_noidangky.setLabelText("Nơi Đăng Ký");

        jLabel2.setText("Ngày sinh");

        jLabel3.setText("Ngày đăng ký");

        jLabel4.setText("Ngày cấp");

        jDateNgayCap.setBackground(new java.awt.Color(255, 255, 255));
        jDateNgayCap.setEnabled(false);

        jDateNgaySinh.setBackground(new java.awt.Color(255, 255, 255));
        jDateNgaySinh.setEnabled(false);

        jDateNgayDangKy.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("Ngày đến");

        jLabel6.setText("Ngày đi");

        btn_xoaDuLieu1.setBackground(new java.awt.Color(18, 99, 63));
        btn_xoaDuLieu1.setForeground(new java.awt.Color(255, 255, 255));
        btn_xoaDuLieu1.setText("Xóa dữ liệu");
        btn_xoaDuLieu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaDuLieu1ActionPerformed(evt);
            }
        });

        tbl_thongTinTamTru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã tạm trú", "Ngày đăng ký", "Ngày đến", "Ngày đi", "Họ tên", "Ngày sinh", "Giới tính", "Số CCCD", "Nơi cấp CCCD", "Ngày cấp CCCD", "Lý do", "Số điện thoại", "Email", "Nơi đăng ký"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_thongTinTamTru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_thongTinTamTruMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_thongTinTamTru);

        tf_hoTen1.setEditable(false);
        tf_hoTen1.setLabelText("Họ và tên");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_maTamTru, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_lyDo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_soCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_hoTen1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_noiCapCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateNgayDi, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jDateNgayCap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addComponent(jDateDen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_gioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_soDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jDateNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addComponent(tf_noidangky, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDateNgayDangKy, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)))
                            .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 899, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125)
                        .addComponent(btn_luu, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131)
                        .addComponent(btn_xoaDuLieu1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tf_hoTen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tf_gioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tf_maTamTru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jDateNgayCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tf_noiCapCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jDateNgayDi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tf_soCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tf_lyDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateNgayDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_soDienThoai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_noidangky, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_luu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_xoaDuLieu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    private void parseAndSetDate(JDateChooser dateChooser, String dateString, String errorMessage) {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        try {
            Date date = dateFormat.parse(dateString);
            dateChooser.setDate(date);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, errorMessage, "Lỗi Định Dạng Ngày", JOptionPane.ERROR_MESSAGE);
            dateChooser.requestFocus();
        }
    }
    public boolean validateDates(Date ngayDen, Date ngayDi, Date ngayDk) {
       if (ngayDen.after(ngayDk)) {
           JOptionPane.showMessageDialog(TamTruControllerUser.this, "Ngày đến không được sau ngày đăng ký.", "Fill all information", JOptionPane.WARNING_MESSAGE);           
           return false;
       } 
       if (ngayDi.before(ngayDen)) {
           JOptionPane.showMessageDialog(TamTruControllerUser.this, "Ngày đi không được trước ngày đến.", "Fill all information", JOptionPane.WARNING_MESSAGE);
           return false;
       } 
       if (ngayDi.before(ngayDk)) {
           JOptionPane.showMessageDialog(TamTruControllerUser.this, "Ngày đi không được trước ngày đăng ký.", "Fill all information", JOptionPane.WARNING_MESSAGE);
           return false;
       } 
       return true;
   }
    private void btn_luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luuActionPerformed
        if (isDuplicateEntry(listTamTru)) {
            JOptionPane.showMessageDialog(TamTruControllerUser.this, "Đơn đã tồn tại.", "Form exist", JOptionPane.WARNING_MESSAGE);
            return;
        } else if (isFormEmpty()) {
            JOptionPane.showMessageDialog(TamTruControllerUser.this, "Vui lòng điền đầy đủ thông tin.", "Fill all information", JOptionPane.WARNING_MESSAGE);
            return;
        } else if (!validateDates(jDateDen.getDate(), jDateNgayDi.getDate(), jDateNgayDangKy.getDate())) {
//            JOptionPane.showMessageDialog(TamTruControllerUser.this, "Vui lòng nhập lại ngày.", "Lỗi định dạng", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            // Assuming you have UI components that correspond to each model property
            String MaTT = "";
            String HoTen = tf_gioiTinh.getText();
            String GioiTinh = tf_gioiTinh.getText();
            Date NgaySinh = jDateNgaySinh.getDate(); // For JDateChooser
            Date NgayDk = new Date(); // Current date or from a date picker
            String CCCD = tf_soCCCD.getText();
            String NoiCap = tf_noiCapCCCD.getText();
            Date NgayCap = jDateNgayCap.getDate(); // For JDateChooser
            String Sdt = tf_soDienThoai.getText();
            String Email = tf_email.getText();
            String LiDo = tf_lyDo.getText();
            Date NgayDen = jDateDen.getDate(); // For JDateChooser
            Date NgayDi = jDateNgayDi.getDate(); // For JDateChooser
            String NoiDangKy = tf_noidangky.getText();
            int TrangThai = 2;

            // Create a new instance of DonTamTruUser with all properties
            DonTamTruUser model = new DonTamTruUser(MaTT, HoTen, GioiTinh, NgaySinh, NgayDk, CCCD, NoiCap, NgayCap, Sdt, Email, LiDo, NgayDen, NgayDi, NoiDangKy, TrangThai);
            // Call the service to insert the new DonTamTruUser into the database
            boolean success = tamTruService.insert(model);

            // Display the result to the user
            if (success) {
                JOptionPane.showMessageDialog(null, "Thêm mới thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                // Additional actions (e.g., clearing form, updating a list, etc.)
            }
            showTable();
        }
    }//GEN-LAST:event_btn_luuActionPerformed
    public boolean isDuplicateEntry(List<DonTamTruUser> listTamTru) {
        // Retrieve values from GUI components
        String hoTen = tf_gioiTinh.getText();
        String gioiTinh = tf_gioiTinh.getText();
        Date ngaySinh = jDateNgaySinh.getDate();
        Date ngayDk = jDateNgayDangKy.getDate();
        String cccd = tf_soCCCD.getText();
        String noiCap = tf_noiCapCCCD.getText();
        Date ngayCap = jDateNgayCap.getDate();
        String sdt = tf_soDienThoai.getText();
        String email = tf_email.getText();
        String lyDo = tf_lyDo.getText();
        Date ngayDen = jDateDen.getDate();
        Date ngayDi = jDateNgayDi.getDate();
        String noiDangKy = tf_noidangky.getText();

        // Loop through the list and compare entries
        for (DonTamTruUser tamTru : listTamTru) {
            if (tamTru.getHoTen().equals(hoTen)
                    && tamTru.getGioiTinh().equals(gioiTinh)
                    && tamTru.getNgaySinh().equals(ngaySinh)
                    && tamTru.getNgayDk().equals(ngayDk)
                    && tamTru.getCCCD().equals(cccd)
                    && tamTru.getNoiCap().equals(noiCap)
                    && tamTru.getNgayCap().equals(ngayCap)
                    && tamTru.getSdt().equals(sdt)
                    && tamTru.getEmail().equals(email)
                    && tamTru.getLiDo().equals(lyDo)
                    && tamTru.getNgayDen().equals(ngayDen)
                    && tamTru.getNgayDi().equals(ngayDi)
                    && tamTru.getNoiDangKy().equals(noiDangKy)) {
                return true; // Duplicate found
            }
        }
        return false; // No duplicates found
    }

    private boolean isFormEmpty() {
        if (tf_lyDo.getText().trim().isEmpty()
                || tf_noidangky.getText().trim().isEmpty()) {
            return true;
        }
        if (jDateDen.getDate() == null
                || jDateNgayDi.getDate() == null) {
            return true;
        }
        return false;
    }

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        clear();
        showInfo();
        btn_luu.setVisible(true); // Make the save button visible
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_xoaDuLieu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaDuLieu1ActionPerformed
        clear();
    }//GEN-LAST:event_btn_xoaDuLieu1ActionPerformed

    private void tbl_thongTinTamTruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_thongTinTamTruMouseClicked
               
        DefaultTableModel model = (DefaultTableModel) tbl_thongTinTamTru.getModel();

        // Setting non-date values
        tf_maTamTru.setText(model.getValueAt(tbl_thongTinTamTru.getSelectedRow(), 0).toString());
        tf_hoTen1.setText(model.getValueAt(tbl_thongTinTamTru.getSelectedRow(), 4).toString());
        tf_gioiTinh.setText(model.getValueAt(tbl_thongTinTamTru.getSelectedRow(), 6).toString());
        tf_soCCCD.setText(model.getValueAt(tbl_thongTinTamTru.getSelectedRow(), 7).toString());
        tf_noiCapCCCD.setText(model.getValueAt(tbl_thongTinTamTru.getSelectedRow(), 8).toString());
        tf_lyDo.setText(model.getValueAt(tbl_thongTinTamTru.getSelectedRow(), 10).toString());
        tf_soDienThoai.setText(model.getValueAt(tbl_thongTinTamTru.getSelectedRow(), 11).toString());
        tf_email.setText(model.getValueAt(tbl_thongTinTamTru.getSelectedRow(), 12).toString());
        tf_noidangky.setText(model.getValueAt(tbl_thongTinTamTru.getSelectedRow(), 13).toString());

        // Setting dates with individual try-catch blocks
        parseAndSetDate(jDateNgayDangKy, model.getValueAt(tbl_thongTinTamTru.getSelectedRow(), 1).toString(), "Ngày đăng ký không hợp lệ. Vui lòng kiểm tra lại.");
        parseAndSetDate(jDateDen, model.getValueAt(tbl_thongTinTamTru.getSelectedRow(), 2).toString(), "Ngày đến không hợp lệ. Vui lòng kiểm tra lại.");
        parseAndSetDate(jDateNgayDi, model.getValueAt(tbl_thongTinTamTru.getSelectedRow(), 3).toString(), "Ngày đi không hợp lệ. Vui lòng kiểm tra lại.");
        parseAndSetDate(jDateNgaySinh, model.getValueAt(tbl_thongTinTamTru.getSelectedRow(), 5).toString(), "Ngày sinh không hợp lệ. Vui lòng kiểm tra lại.");
        parseAndSetDate(jDateNgayCap, model.getValueAt(tbl_thongTinTamTru.getSelectedRow(), 9).toString(), "Ngày cấp CCCD không hợp lệ. Vui lòng kiểm tra lại.");

    }//GEN-LAST:event_tbl_thongTinTamTruMouseClicked

    private void clear() {
        tf_soCCCD.setText("");
        tf_gioiTinh.setText("");
        tf_maTamTru.setText("");
        tf_noiCapCCCD.setText("");
        tf_soDienThoai.setText("");
        tf_email.setText("");
        tf_noidangky.setText("");
        tf_lyDo.setText("");
        tf_gioiTinh.setText("");
        jDateNgaySinh.setDate(null);
        jDateNgayCap.setDate(null);
        jDateNgayDangKy.setDate(null);
        jDateDen.setDate(null);
        jDateNgayDi.setDate(null);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Swing.Button btn_luu;
    private Swing.Button btn_them;
    private Swing.Button btn_xoaDuLieu1;
    private com.toedter.calendar.JDateChooser jDateDen;
    private com.toedter.calendar.JDateChooser jDateNgayCap;
    private com.toedter.calendar.JDateChooser jDateNgayDangKy;
    private com.toedter.calendar.JDateChooser jDateNgayDi;
    private com.toedter.calendar.JDateChooser jDateNgaySinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private Swing.TableDark tbl_thongTinTamTru;
    private Swing.TextField tf_email;
    private Swing.TextField tf_gioiTinh;
    private Swing.TextField tf_hoTen1;
    private Swing.TextField tf_lyDo;
    private Swing.TextField tf_maTamTru;
    private Swing.TextField tf_noiCapCCCD;
    private Swing.TextField tf_noidangky;
    private Swing.TextField tf_soCCCD;
    private Swing.TextField tf_soDienThoai;
    // End of variables declaration//GEN-END:variables
}
