/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Controller.User;

import Controller.Admin.Login_RegisterController;
import InterfaceService.ICongDanService;
import InterfaceService.ITamVangService;
import Models.CongDanModel;
import Models.DonTamVangUser;
import ServiceImplement.CongDanServiceImpl;
import ServiceImplement.TamVangServiceImpl;
import com.toedter.calendar.JDateChooser;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.text.ParseException;     

/**
 *
 * @author Acer
 */
public class TamVangControllerUser extends javax.swing.JPanel {

    /**
     * Creates new form TamTruControllerUser
     */
    DefaultTableModel model;
    List<DonTamVangUser> listTamVang;
    ITamVangService tamVangService = new TamVangServiceImpl();
    ICongDanService CongDanService = new CongDanServiceImpl();
    CongDanModel cd = new CongDanModel();
    public TamVangControllerUser() {
        initComponents();
        model = (DefaultTableModel) tbl_thongTinTamVang.getModel();    
        showInfo();
        
        showTable();
    }
    private void showTable() {
        model.setRowCount(0);
        listTamVang = tamVangService.findAllTVuser(Login_RegisterController.AppContext.userName);
        for (DonTamVangUser tamVang : listTamVang) {
            model.addRow(new Object[]{tamVang.getMaTV(),tamVang.getHoTen(), tamVang.getGioiTinh(), tamVang.getNgaySinh(),tamVang.getNgayDk(), tamVang.getCCCD(), tamVang.getNoiCap(), tamVang.getNgayCap(),    tamVang.getSdt(), tamVang.getEmail(), tamVang.getNoiChuyenDi(), tamVang.getNoiChuyenDen(), tamVang.getNgayDi(), tamVang.getNgayVe(), tamVang.getLydo()});
        }
    }
    private void showInfo(){
        cd = CongDanService.findOne(Login_RegisterController.AppContext.userName);
        tf_hoTen.setText(cd.getHoTen());
        tf_soCCCD.setText(cd.getCCCD());
        jDateNgaySinh.setDate(cd.getNgaySinh());
        jDateNgayCap.setDate(cd.getNgcCccd());
        tf_noiCapCCCD.setText(cd.getNcCccd());
        tf_soDienThoai.setText(cd.getSDT());
        tf_email.setText(cd.getEmail());
        combo_GioiTinh.setSelectedItem(cd.getGioiTinh());
        jDateNgayDangKy.setDate(new java.util.Date());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tf_hoTen = new Swing.TextField();
        tf_noiCapCCCD = new Swing.TextField();
        tf_soCCCD = new Swing.TextField();
        tf_email = new Swing.TextField();
        tf_maTamVang = new Swing.TextField();
        tf_soDienThoai = new Swing.TextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_thongTinTamVang = new javax.swing.JTable();
        btn_them = new Swing.Button();
        jLabel1 = new javax.swing.JLabel();
        btn_luu = new Swing.Button();
        tf_lyDo = new Swing.TextField();
        tf_noichuyenden = new Swing.TextField();
        combo_GioiTinh = new Swing.Combobox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDateNgayCap = new com.toedter.calendar.JDateChooser();
        jDateNgaySinh = new com.toedter.calendar.JDateChooser();
        jDateNgayDangKy = new com.toedter.calendar.JDateChooser();
        jDateNgayVe = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jDateNgayDi = new com.toedter.calendar.JDateChooser();
        btn_xoaDuLieu1 = new Swing.Button();
        tf_noichuyendi = new Swing.TextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tf_hoTen.setEditable(false);
        tf_hoTen.setLabelText("Họ và tên");

        tf_noiCapCCCD.setEditable(false);
        tf_noiCapCCCD.setLabelText("Nơi cấp CCCD");

        tf_soCCCD.setEditable(false);
        tf_soCCCD.setLabelText("Số CCCD");

        tf_email.setEditable(false);
        tf_email.setLabelText("Email");

        tf_maTamVang.setEditable(false);
        tf_maTamVang.setLabelText("Mã tạm vắng");

        tf_soDienThoai.setEditable(false);
        tf_soDienThoai.setLabelText("Số điện thoại");

        tbl_thongTinTamVang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Tạm Vắng", "Họ tên", "Giới tính", "Ngày sinh", "Ngày đăng ký", "Số CCCD", "Nơi cấp CCCD", "Ngày cấp", "Số điện thoại", "Email", "Nơi chuyển đến", "Nơi chuyển đi", "Ngày đi", "Ngày về", "Lý do"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_thongTinTamVang.setShowGrid(false);
        tbl_thongTinTamVang.getTableHeader().setReorderingAllowed(false);
        tbl_thongTinTamVang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_thongTinTamVangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_thongTinTamVang);

        btn_them.setBackground(new java.awt.Color(18, 99, 63));
        btn_them.setForeground(new java.awt.Color(255, 255, 255));
        btn_them.setText("Đăng ký đơn");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("THÔNG TIN TẠM VẮNG");

        btn_luu.setBackground(new java.awt.Color(18, 99, 63));
        btn_luu.setForeground(new java.awt.Color(255, 255, 255));
        btn_luu.setText("Lưu");
        btn_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luuActionPerformed(evt);
            }
        });

        tf_lyDo.setLabelText("Lý do");

        tf_noichuyenden.setLabelText("Nơi Chuyển Đến");

        combo_GioiTinh.setEditable(true);
        combo_GioiTinh.setLabeText("Giới tính");
        combo_GioiTinh.setName(""); // NOI18N

        jLabel2.setText("Ngày sinh");

        jLabel3.setText("Ngày đăng ký");

        jLabel4.setText("Ngày cấp");

        jDateNgayCap.setEnabled(false);

        jDateNgaySinh.setEnabled(false);

        jDateNgayDangKy.setEnabled(false);

        jLabel5.setText("Ngày về");

        jLabel6.setText("Ngày đi");

        btn_xoaDuLieu1.setBackground(new java.awt.Color(18, 99, 63));
        btn_xoaDuLieu1.setForeground(new java.awt.Color(255, 255, 255));
        btn_xoaDuLieu1.setText("Xóa dữ liệu");
        btn_xoaDuLieu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaDuLieu1ActionPerformed(evt);
            }
        });

        tf_noichuyendi.setLabelText("Nơi Chuyển Đi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(358, 358, 358)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tf_noichuyendi, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(tf_maTamVang, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(tf_soCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(tf_hoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(tf_noiCapCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jDateNgayCap, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(12, 12, 12)
                                                .addComponent(tf_soDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(combo_GioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel2)
                                                    .addComponent(jDateNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jDateNgayDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3)
                                            .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tf_noichuyenden, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jDateNgayDi, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jDateNgayVe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(tf_lyDo, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 845, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_luu, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_xoaDuLieu1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(459, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_hoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_maTamVang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(combo_GioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateNgayDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_soDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateNgayVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tf_soCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tf_noiCapCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateNgayCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jDateNgayDi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tf_lyDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tf_noichuyenden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tf_noichuyendi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_luu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_xoaDuLieu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_thongTinTamVangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_thongTinTamVangMouseClicked
       
        DefaultTableModel model = (DefaultTableModel) tbl_thongTinTamVang.getModel();

        // Setting non-date values
        tf_maTamVang.setText(model.getValueAt(tbl_thongTinTamVang.getSelectedRow(), 0).toString());
        tf_hoTen.setText(model.getValueAt(tbl_thongTinTamVang.getSelectedRow(), 1).toString());
        combo_GioiTinh.setSelectedItem(model.getValueAt(tbl_thongTinTamVang.getSelectedRow(), 2).toString());
        tf_soCCCD.setText(model.getValueAt(tbl_thongTinTamVang.getSelectedRow(), 5).toString());
        tf_noiCapCCCD.setText(model.getValueAt(tbl_thongTinTamVang.getSelectedRow(), 6).toString());
        tf_lyDo.setText(model.getValueAt(tbl_thongTinTamVang.getSelectedRow(), 14).toString());
        tf_soDienThoai.setText(model.getValueAt(tbl_thongTinTamVang.getSelectedRow(), 8).toString());
        tf_email.setText(model.getValueAt(tbl_thongTinTamVang.getSelectedRow(), 9).toString());
        tf_noichuyenden.setText(model.getValueAt(tbl_thongTinTamVang.getSelectedRow(), 10).toString());
        tf_noichuyendi.setText(model.getValueAt(tbl_thongTinTamVang.getSelectedRow(), 11).toString());
        // Setting dates with individual try-catch blocks
        parseAndSetDate(jDateNgayDangKy, model.getValueAt(tbl_thongTinTamVang.getSelectedRow(), 4).toString(), "Ngày đăng ký không hợp lệ. Vui lòng kiểm tra lại.");
        parseAndSetDate(jDateNgayVe, model.getValueAt(tbl_thongTinTamVang.getSelectedRow(), 13).toString(), "Ngày về không hợp lệ. Vui lòng kiểm tra lại.");
        parseAndSetDate(jDateNgayDi, model.getValueAt(tbl_thongTinTamVang.getSelectedRow(), 12).toString(), "Ngày đi không hợp lệ. Vui lòng kiểm tra lại.");
        parseAndSetDate(jDateNgaySinh, model.getValueAt(tbl_thongTinTamVang.getSelectedRow(), 3).toString(), "Ngày sinh không hợp lệ. Vui lòng kiểm tra lại.");
        parseAndSetDate(jDateNgayCap, model.getValueAt(tbl_thongTinTamVang.getSelectedRow(), 7).toString(), "Ngày cấp CCCD không hợp lệ. Vui lòng kiểm tra lại.");

    }//GEN-LAST:event_tbl_thongTinTamVangMouseClicked
    private void parseAndSetDate(JDateChooser dateChooser, String dateString, String errorMessage) {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        try {
            Date date = dateFormat.parse(dateString);
            dateChooser.setDate(date);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, errorMessage, "Lỗi Định Dạng Ngày", JOptionPane.ERROR_MESSAGE);
            dateChooser.requestFocus();
        }
    }
    private void btn_luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luuActionPerformed

        if (isDuplicateEntry(listTamVang)) {
            System.out.println("hihi");
            JOptionPane.showMessageDialog(TamVangControllerUser.this,"Đơn đã tồn tại.","Form exist",JOptionPane.WARNING_MESSAGE);
        } else if(isFormEmpty()){
            System.out.println("hihi2");
            JOptionPane.showMessageDialog(TamVangControllerUser.this,"Vui lòng điền đầy đủ thông tin.","Fill all information",JOptionPane.WARNING_MESSAGE);
        } else if(validateDates(jDateNgayDi.getDate(),jDateNgayDangKy.getDate(),jDateNgayVe.getDate())){
            System.out.println("hihi3");
            JOptionPane.showMessageDialog(TamVangControllerUser.this,"Nhập lại ngày.","Form exist",JOptionPane.WARNING_MESSAGE);
        }else {
            // Assuming you have UI components that correspond to each model property
            String MaTV = "";
            String HoTen = tf_hoTen.getText();
            String GioiTinh = combo_GioiTinh.getSelectedItem().toString(); // Assuming JComboBox for gender
            Date NgaySinh = jDateNgaySinh.getDate(); // For JDateChooser
            Date NgayDk = new Date(); // Current date or from a date picker
            String CCCD = tf_soCCCD.getText();
            String NoiCap = tf_noiCapCCCD.getText();
            Date NgayCap = jDateNgayCap.getDate(); // For JDateChooser
            String Sdt = tf_soDienThoai.getText();
            String Email = tf_email.getText();
            String LiDo = tf_lyDo.getText();
            Date NgayDen = jDateNgayVe.getDate(); // For JDateChooser
            Date NgayDi = jDateNgayDi.getDate(); // For JDateChooser
            String NoiChuyenDen = tf_noichuyenden.getText();
            String NoiChuyenDi = tf_noichuyendi.getText();
            int TrangThai = 1;
            // Create a new instance of DonTamTruUser with all properties
            DonTamVangUser model = new DonTamVangUser(MaTV, HoTen, GioiTinh, NgaySinh, NgayDk, CCCD, NoiCap, NgayCap, Sdt, Email, NoiChuyenDen, NoiChuyenDi, NgayDi, NgayDen, LiDo, TrangThai);

            // Call the service to insert the new DonTamTruUser into the database
            boolean success = tamVangService.insertUser(model);
            // Display the result to the user
            if(success) {
                JOptionPane.showMessageDialog(null, "Thêm mới thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                // Additional actions (e.g., clearing form, updating a list, etc.)
            }
            showTable();
        }
    }//GEN-LAST:event_btn_luuActionPerformed
    public boolean isDuplicateEntry(List<DonTamVangUser> listTamVang) {
        // Retrieve values from GUI components
        String MaTV = "";
        String hoTen = tf_hoTen.getText();
        String gioiTinh = (String) combo_GioiTinh.getSelectedItem();
        Date ngaySinh = jDateNgaySinh.getDate();
        String cccd = tf_soCCCD.getText();
        String noiCap = tf_noiCapCCCD.getText();
        Date ngayCap = jDateNgayCap.getDate();
        String sdt = tf_soDienThoai.getText();
        String email = tf_email.getText();
        String lyDo = tf_lyDo.getText();
        Date ngayVe = jDateNgayVe.getDate();
        Date ngayDi = jDateNgayDi.getDate();
        String noiChuyenDen = tf_noichuyenden.getText();
        String noiChuyenDi = tf_noichuyendi.getText();
        
        // Loop through the list and compare entries
        for (DonTamVangUser tamVang : listTamVang) {
             System.out.println("Comparing against record: Name=" + tamVang.getHoTen() + ", Gender=" + tamVang.getGioiTinh());
            
            if (tamVang.getHoTen().equals(hoTen)) {
                System.out.println("Name matches");
            }
            if (tamVang.getGioiTinh().equals(gioiTinh)) {
                System.out.println("Gender matches");
            }
            if (tamVang.getNgaySinh().equals(ngaySinh)) {
                System.out.println("Birth date matches");
            }
            if (tamVang.getCCCD().equals(cccd)) {
                System.out.println("CCCD matches");
            }
            if (tamVang.getNoiCap().equals(noiCap)) {
                System.out.println("Issue place matches");
            }
            if (tamVang.getNgayCap().equals(ngayCap)) {
                System.out.println("Issue date matches");
            }
            if (tamVang.getSdt().equals(sdt)) {
                System.out.println("Phone number matches");
            }
            if (tamVang.getEmail().equals(email)) {
                System.out.println("Email matches");
            }
            if (tamVang.getLydo().equals(lyDo)) {
                System.out.println("Reason matches");
            }
            if (tamVang.getNgayVe().equals(ngayVe)) {
                System.out.println("Return date matches");
            }
            if (tamVang.getNgayDi().equals(ngayDi)) {
                System.out.println("Departure date matches");
            }
            if (tamVang.getNoiChuyenDen().equals(noiChuyenDen)) {
                System.out.println("Transfer to location matches");
            }
            if (tamVang.getNoiChuyenDi().equals(noiChuyenDi)) {
                System.out.println("Transfer from location matches");
            }
            if (tamVang.getHoTen().equals(hoTen) &&
                tamVang.getGioiTinh().equals(gioiTinh) &&
                tamVang.getNgaySinh().equals(ngaySinh) &&
                tamVang.getCCCD().equals(cccd) &&
                tamVang.getNoiCap().equals(noiCap) &&
                tamVang.getNgayCap().equals(ngayCap) &&
                tamVang.getSdt().equals(sdt) &&
                tamVang.getEmail().equals(email) &&
                tamVang.getLydo().equals(lyDo) &&
                tamVang.getNgayVe().equals(ngayVe) &&
                tamVang.getNgayDi().equals(ngayDi) &&
                tamVang.getNoiChuyenDen().equals(noiChuyenDen) &&
                tamVang.getNoiChuyenDi().equals(noiChuyenDi)){
                System.out.println("co trung");
                return true; // Duplicate found
            }
        }
        System.out.println("khong trung");
        return false; // No duplicates found
    }
    private boolean isFormEmpty() {
        if (tf_lyDo.getText().trim().isEmpty() ||
            tf_noichuyenden.getText().trim().isEmpty()||
            tf_noichuyendi.getText().trim().isEmpty()) {
            return true;
        }
        if (jDateNgayVe.getDate() == null ||
            jDateNgayDi.getDate() == null) {
            return true;
        }
        return false;
    }
    public boolean validateDates(Date ngayDi, Date ngayDk, Date ngayVe) {
        // Check if ngayDi (departure date) is on or before ngayDk (registration date)
        if (ngayDi.after(ngayDk)) {
            System.out.println("Departure date must be on or before the registration date.");
            return false;
        }
        // Check if ngayVe (return date) is on or before ngayDi (departure date)
        if (ngayVe.before(ngayDi)) {
            System.out.println("Return date must be on or after the departure date.");
            return false;
        }
        if (ngayVe.before(ngayDk)) {
            System.out.println("Return date must be on or after the departure date.");
            return false;
        }
        return true; // Both conditions are satisfied
    }   
    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        clear();
        showInfo();
        btn_luu.setVisible(true); // Make the save button visible
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_xoaDuLieu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaDuLieu1ActionPerformed
        clear();
    }//GEN-LAST:event_btn_xoaDuLieu1ActionPerformed

    private void clear() {
        tf_soCCCD.setText("");
        tf_hoTen.setText("");
        tf_maTamVang.setText("");
        tf_noiCapCCCD.setText("");
        tf_soDienThoai.setText("");
        tf_email.setText("");
        tf_noichuyenden.setText("");
        tf_noichuyendi.setText("");
        tf_lyDo.setText("");
        combo_GioiTinh.setSelectedIndex(-1); 
        jDateNgaySinh.setDate(null);
        jDateNgayCap.setDate(null);
        jDateNgayDangKy.setDate(null);
        jDateNgayVe.setDate(null);
        jDateNgayDi.setDate(null);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Swing.Button btn_luu;
    private Swing.Button btn_them;
    private Swing.Button btn_xoaDuLieu1;
    private Swing.Combobox combo_GioiTinh;
    private com.toedter.calendar.JDateChooser jDateNgayCap;
    private com.toedter.calendar.JDateChooser jDateNgayDangKy;
    private com.toedter.calendar.JDateChooser jDateNgayDi;
    private com.toedter.calendar.JDateChooser jDateNgaySinh;
    private com.toedter.calendar.JDateChooser jDateNgayVe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_thongTinTamVang;
    private Swing.TextField tf_email;
    private Swing.TextField tf_hoTen;
    private Swing.TextField tf_lyDo;
    private Swing.TextField tf_maTamVang;
    private Swing.TextField tf_noiCapCCCD;
    private Swing.TextField tf_noichuyenden;
    private Swing.TextField tf_noichuyendi;
    private Swing.TextField tf_soCCCD;
    private Swing.TextField tf_soDienThoai;
    // End of variables declaration//GEN-END:variables
}
