package Controller.User;

import Controller.Admin.Login_RegisterController;
import InterfaceService.IThueService;
import Models.ThueModel;
import ServiceImplement.ThueServiceImpl;


public class ThongTinThueControllerUser extends javax.swing.JPanel {


    public ThongTinThueControllerUser() {
        initComponents();
        IThueService ThueService = new ThueServiceImpl();
        String currentUser = Login_RegisterController.AppContext.userName;
        ThueModel thue = ThueService.findOneByCCCD(currentUser, currentUser);
        
        tf_maSoThue.setText(thue.getMasothue());
        tf_tenNguoiNopThue.setText(thue.getHoten());
        tf_coQuanThue.setText(thue.getCoquanthue());
        tf_soCCCD.setText(currentUser);
        tf_ngayThayDoiGanNhat.setText(thue.getNgaythaydoithongtingannhat().toString());                        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tf_maSoThue = new Swing.TextField();
        tf_tenNguoiNopThue = new Swing.TextField();
        tf_coQuanThue = new Swing.TextField();
        tf_soCCCD = new Swing.TextField();
        tf_ngayThayDoiGanNhat = new Swing.TextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("THÔNG TIN THUẾ");

        tf_maSoThue.setEditable(false);
        tf_maSoThue.setLabelText("Mã số thuế");

        tf_tenNguoiNopThue.setEditable(false);
        tf_tenNguoiNopThue.setLabelText("Tên người nộp thuế");

        tf_coQuanThue.setEditable(false);
        tf_coQuanThue.setLabelText("Cơ quan thuế");

        tf_soCCCD.setEditable(false);
        tf_soCCCD.setLabelText("Số CCCD");

        tf_ngayThayDoiGanNhat.setEditable(false);
        tf_ngayThayDoiGanNhat.setLabelText("Ngày thay đổi thông tin gần nhất");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(tf_soCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(tf_ngayThayDoiGanNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tf_maSoThue, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(tf_tenNguoiNopThue, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(tf_coQuanThue, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(jLabel1)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_maSoThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_coQuanThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_tenNguoiNopThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_soCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_ngayThayDoiGanNhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(173, 173, 173))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private Swing.TextField tf_coQuanThue;
    private Swing.TextField tf_maSoThue;
    private Swing.TextField tf_ngayThayDoiGanNhat;
    private Swing.TextField tf_soCCCD;
    private Swing.TextField tf_tenNguoiNopThue;
    // End of variables declaration//GEN-END:variables

}
