package Controller.User;

import Controller.Admin.Login_RegisterController;
import InterfaceService.IHoKhauService;
import Models.ThongTinHoKhau;
import ServiceImplement.HoKhauServiceImpl;
import java.util.List;
import javax.swing.table.DefaultTableModel;


public class ThongTinHoKhauControllerUser extends javax.swing.JPanel {
    
    DefaultTableModel model;
    List<ThongTinHoKhau> listHoKhau;
    IHoKhauService hoKhauService = new HoKhauServiceImpl();
    
    public ThongTinHoKhauControllerUser() {
        initComponents();
        String currentUser = Login_RegisterController.AppContext.userName;
        ThongTinHoKhau hk = hoKhauService.findOneByCCCD(currentUser);

        model = (DefaultTableModel)tb_HK.getModel();
        
        tf_maKhaiSinhChuHo.setText(hk.getCCCDChuHo());
        tf_maHoKhau.setText(hk.getMaHoKhau());
        tf_hoTenChuHo.setText(hk.getHoTenChuHo());
        tf_diaChi.setText(hk.getDiaChi());
        tf_hoTenNguoiDangNhap.setText(hk.getHoTenNguoiDangNhap());
        tf_maKhaiSinhNguoiDangNhap.setText(hk.getCCCDNguoiDangNhap());
        tf_quanHeChuHo.setText(hk.getQuanHeVoiChuHo());
        
        listHoKhau = hoKhauService.findAllHoKhauUser(tf_maHoKhau.getText().trim());
        showTable();
    }
    
    private void showTable() {
        for (ThongTinHoKhau hoKhau : listHoKhau) {
            model.addRow(new Object[]{hoKhau.getMaHoKhau(), hoKhau.getKhaiSinhChuHo(), hoKhau.getHoTenChuHo(), hoKhau.getKhaiSinhNguoiThamGia(), hoKhau.getHoTenNguoiThan(), hoKhau.getQuanHeVoiChuHo(), hoKhau.getDiaChi()});
        }
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf_hoTenChuHo = new Swing.TextField();
        tf_maHoKhau = new Swing.TextField();
        tf_maKhaiSinhNguoiDangNhap = new Swing.TextField();
        tf_maKhaiSinhChuHo = new Swing.TextField();
        tf_hoTenNguoiDangNhap = new Swing.TextField();
        tf_quanHeChuHo = new Swing.TextField();
        jLabel1 = new javax.swing.JLabel();
        tf_diaChi = new Swing.TextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_HK = new Swing.TableDark();

        setBackground(new java.awt.Color(255, 255, 255));

        tf_hoTenChuHo.setEditable(false);
        tf_hoTenChuHo.setLabelText("Họ và tên chủ hộ");

        tf_maHoKhau.setEditable(false);
        tf_maHoKhau.setLabelText("Mã hộ khẩu");

        tf_maKhaiSinhNguoiDangNhap.setEditable(false);
        tf_maKhaiSinhNguoiDangNhap.setLabelText("Mã khai sinh người đăng nhập");

        tf_maKhaiSinhChuHo.setEditable(false);
        tf_maKhaiSinhChuHo.setLabelText("Mã khai sinh chủ hộ");

        tf_hoTenNguoiDangNhap.setEditable(false);
        tf_hoTenNguoiDangNhap.setLabelText("Họ và tên người đăng nhập");

        tf_quanHeChuHo.setEditable(false);
        tf_quanHeChuHo.setLabelText("Quan hệ với chủ hộ");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("THÔNG TIN HỘ KHẨU");

        tf_diaChi.setEditable(false);
        tf_diaChi.setLabelText("Địa chỉ");

        tb_HK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hộ khẩu", "Mã KS chủ hộ", "Họ và tên chủ hộ", "Mã KS người thân", "Họ và tên người thân", "Quan hệ với chủ hộ", "Địa chỉ"
            }
        ));
        jScrollPane1.setViewportView(tb_HK);
        if (tb_HK.getColumnModel().getColumnCount() > 0) {
            tb_HK.getColumnModel().getColumn(0).setPreferredWidth(22);
            tb_HK.getColumnModel().getColumn(1).setPreferredWidth(22);
            tb_HK.getColumnModel().getColumn(2).setPreferredWidth(25);
            tb_HK.getColumnModel().getColumn(3).setPreferredWidth(22);
            tb_HK.getColumnModel().getColumn(4).setPreferredWidth(25);
            tb_HK.getColumnModel().getColumn(5).setPreferredWidth(20);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(361, 361, 361))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_hoTenChuHo, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_hoTenNguoiDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_maKhaiSinhChuHo, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_maKhaiSinhNguoiDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_quanHeChuHo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_maHoKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1)
                    .addComponent(tf_diaChi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 855, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_hoTenChuHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_maHoKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_maKhaiSinhChuHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_hoTenNguoiDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_maKhaiSinhNguoiDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_quanHeChuHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tf_diaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private Swing.TableDark tb_HK;
    private Swing.TextField tf_diaChi;
    private Swing.TextField tf_hoTenChuHo;
    private Swing.TextField tf_hoTenNguoiDangNhap;
    private Swing.TextField tf_maHoKhau;
    private Swing.TextField tf_maKhaiSinhChuHo;
    private Swing.TextField tf_maKhaiSinhNguoiDangNhap;
    private Swing.TextField tf_quanHeChuHo;
    // End of variables declaration//GEN-END:variables

}
