/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Controller.Admin;

import InterfaceService.IChungNhanKetHonService;
import InterfaceService.IKhaiSinhService;
import InterfaceService.ITamTruService;
import InterfaceService.ITamVangService;
import Models.DonChungNhanKetHon;
import Models.DonTamTru;
import Models.DonTamVang;
import Models.KhaiSinhModel;
import ServiceImplement.ChungNhanKetHonServiceImpl;
import ServiceImplement.KhaiSinhServiceImpl;
import ServiceImplement.TamTruServiceImpl;
import ServiceImplement.TamVangServiceImpl;
import java.awt.Component;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class TraCuuDonController extends javax.swing.JPanel {

    private String search = "";
    private DefaultTableModel model;

    public String getSearch() {
        return search;
    }

    public void setSearch(String search) {
        this.search = search;
    }

    public TraCuuDonController() {
        initComponents();
        getSearch();
        if (tabbedPaneCustom1.getSelectedIndex() == 0) {
        }
    }

    private void showForm(Component com) {
        tabbedPaneCustom1.removeAll();
        tabbedPaneCustom1.add(com);
        tabbedPaneCustom1.repaint();
        tabbedPaneCustom1.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDon = new javax.swing.JPanel();
        tf_timkiem = new Swing.TextField();
        jLabel1 = new javax.swing.JLabel();
        tabbedPaneCustom1 = new Swing.TabbedPaneCustom();
        panelXemDon = new javax.swing.JPanel();
        btn_donkhaisinh = new button.MyButton();
        btn_dontamtru = new button.MyButton();
        btn_dontamvang = new button.MyButton();
        btn_thongtincongdan = new button.MyButton();
        btn_donlyhon = new button.MyButton();
        btn_giaychungtu = new button.MyButton();
        btn_donkethon = new button.MyButton();
        panelHoKhau = new javax.swing.JPanel();
        panelThue = new javax.swing.JPanel();
        btn_timkiem = new button.MyButton();
        panelGCNKH = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_cnkh = new javax.swing.JTable();
        btn_backFromGCNKHToDon = new button.MyButton();
        tf_ngaysinhchong = new Swing.TextField();
        tf_ngaydangky = new Swing.TextField();
        tf_quoctichchong = new Swing.TextField();
        tf_noidangky = new Swing.TextField();
        tf_ngaysinhvo = new Swing.TextField();
        tf_quoctichvo = new Swing.TextField();
        tf_dantocchong = new Swing.TextField();
        jLabel2 = new javax.swing.JLabel();
        tf_giaytotuythanchong = new Swing.TextField();
        tf_dantocvo = new Swing.TextField();
        tf_giaytotuythanvo = new Swing.TextField();
        tf_noicutrucuachong = new Swing.TextField();
        tf_hotenchong = new Swing.TextField();
        tf_noicutrucuavo = new Swing.TextField();
        tf_hotenvo = new Swing.TextField();
        tf_macnkh = new Swing.TextField();
        panelTT = new javax.swing.JPanel();
        tf_matamtru = new Swing.TextField();
        tf_hoten = new Swing.TextField();
        tf_ngaysinh = new Swing.TextField();
        tf_cccd = new Swing.TextField();
        tf_noicap = new Swing.TextField();
        tf_ngaycap = new Swing.TextField();
        tf_ngayden = new Swing.TextField();
        tf_ngaydi = new Swing.TextField();
        tf_ngaydangkyTT = new Swing.TextField();
        tf_lydo = new Swing.TextField();
        tf_noidangkyTT = new Swing.TextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_tamtru = new javax.swing.JTable();
        btn_backFromTTToDon = new button.MyButton();
        panelGCT = new javax.swing.JPanel();
        tf_machungtu = new Swing.TextField();
        tf_cccd1 = new Swing.TextField();
        tf_hoten1 = new Swing.TextField();
        tf_ngaysinh1 = new Swing.TextField();
        tf_ngaymat = new Swing.TextField();
        tf_noimat = new Swing.TextField();
        tf_lydo1 = new Swing.TextField();
        myButton1 = new button.MyButton();
        panelKS = new javax.swing.JPanel();
        tf_hotenks = new Swing.TextField();
        tf_maks = new Swing.TextField();
        tf_noisinh = new Swing.TextField();
        tf_gioitinh = new Swing.TextField();
        tf_ngaysinhks = new Swing.TextField();
        tf_quequan = new Swing.TextField();
        tf_dantoc = new Swing.TextField();
        tf_quoctich = new Swing.TextField();
        tf_cccdcha = new Swing.TextField();
        tf_cccdme = new Swing.TextField();
        tf_ngaydangkyks = new Swing.TextField();
        tf_cccdnguoikhaisinh = new Swing.TextField();
        tf_quanhe = new Swing.TextField();
        tf_noidangkyks = new Swing.TextField();
        brn_backFromKSToDon = new button.MyButton();
        panelTV = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tf_hotentv = new Swing.TextField();
        tf_matamvang = new Swing.TextField();
        tf_noichuyendi = new Swing.TextField();
        tf_noichuyenden = new Swing.TextField();
        tf_ngaysinhtv = new Swing.TextField();
        tf_noicaptv = new Swing.TextField();
        tf_cccdtv = new Swing.TextField();
        tf_ngaydangkytv = new Swing.TextField();
        tf_ngayditv = new Swing.TextField();
        tf_ngayve = new Swing.TextField();
        tf_lydotv = new Swing.TextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_tamvang = new javax.swing.JTable();
        btn_backFromTVToDon = new button.MyButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.CardLayout());

        panelDon.setBackground(new java.awt.Color(255, 255, 255));

        tf_timkiem.setLabelText("Nhập CCCD");
        tf_timkiem.setLineColor(new java.awt.Color(255, 0, 51));

        jLabel1.setText("Quản lý đơn");

        tabbedPaneCustom1.setSelectedColor(new java.awt.Color(153, 0, 255));

        panelXemDon.setBackground(new java.awt.Color(255, 255, 255));
        panelXemDon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 255)));

        btn_donkhaisinh.setText("Đơn khai sinh");
        btn_donkhaisinh.setBorderColor(new java.awt.Color(255, 0, 0));
        btn_donkhaisinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_donkhaisinhActionPerformed(evt);
            }
        });

        btn_dontamtru.setText("Đơn tạm trú");
        btn_dontamtru.setBorderColor(new java.awt.Color(255, 0, 0));
        btn_dontamtru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dontamtruActionPerformed(evt);
            }
        });

        btn_dontamvang.setText("Đơn tạm vắng");
        btn_dontamvang.setBorderColor(new java.awt.Color(255, 0, 0));
        btn_dontamvang.setColorClick(new java.awt.Color(255, 255, 255));
        btn_dontamvang.setColorOver(new java.awt.Color(255, 102, 102));
        btn_dontamvang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dontamvangActionPerformed(evt);
            }
        });

        btn_thongtincongdan.setText("Thông tin công dân");
        btn_thongtincongdan.setBorderColor(new java.awt.Color(255, 0, 0));
        btn_thongtincongdan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thongtincongdanActionPerformed(evt);
            }
        });

        btn_donlyhon.setText("Đơn ly hôn");
        btn_donlyhon.setBorderColor(new java.awt.Color(255, 0, 0));
        btn_donlyhon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_donlyhonActionPerformed(evt);
            }
        });

        btn_giaychungtu.setText("Giấy chứng tử");
        btn_giaychungtu.setBorderColor(new java.awt.Color(255, 0, 0));
        btn_giaychungtu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_giaychungtuActionPerformed(evt);
            }
        });

        btn_donkethon.setText("Đơn kết hôn");
        btn_donkethon.setBorderColor(new java.awt.Color(255, 0, 0));
        btn_donkethon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_donkethonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelXemDonLayout = new javax.swing.GroupLayout(panelXemDon);
        panelXemDon.setLayout(panelXemDonLayout);
        panelXemDonLayout.setHorizontalGroup(
            panelXemDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelXemDonLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(btn_donkethon, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btn_donkhaisinh, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btn_dontamtru, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btn_dontamvang, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelXemDonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_thongtincongdan, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btn_donlyhon, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btn_giaychungtu, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
        );
        panelXemDonLayout.setVerticalGroup(
            panelXemDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelXemDonLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(panelXemDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_donkhaisinh, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_dontamtru, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_dontamvang, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_donkethon, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(panelXemDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_thongtincongdan, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_donlyhon, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_giaychungtu, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(361, Short.MAX_VALUE))
        );

        tabbedPaneCustom1.addTab("Xem đơn từ", panelXemDon);

        panelHoKhau.setBackground(new java.awt.Color(255, 255, 255));
        panelHoKhau.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 255)));

        javax.swing.GroupLayout panelHoKhauLayout = new javax.swing.GroupLayout(panelHoKhau);
        panelHoKhau.setLayout(panelHoKhauLayout);
        panelHoKhauLayout.setHorizontalGroup(
            panelHoKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 875, Short.MAX_VALUE)
        );
        panelHoKhauLayout.setVerticalGroup(
            panelHoKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 733, Short.MAX_VALUE)
        );

        tabbedPaneCustom1.addTab("Hộ khẩu", panelHoKhau);

        panelThue.setBackground(new java.awt.Color(255, 255, 255));
        panelThue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 255)));

        javax.swing.GroupLayout panelThueLayout = new javax.swing.GroupLayout(panelThue);
        panelThue.setLayout(panelThueLayout);
        panelThueLayout.setHorizontalGroup(
            panelThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 875, Short.MAX_VALUE)
        );
        panelThueLayout.setVerticalGroup(
            panelThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 733, Short.MAX_VALUE)
        );

        tabbedPaneCustom1.addTab("Thuế", panelThue);

        btn_timkiem.setBackground(new java.awt.Color(255, 0, 0));
        btn_timkiem.setForeground(new java.awt.Color(255, 255, 255));
        btn_timkiem.setText("Search");
        btn_timkiem.setBorderColor(new java.awt.Color(255, 0, 0));
        btn_timkiem.setRadius(15);
        btn_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDonLayout = new javax.swing.GroupLayout(panelDon);
        panelDon.setLayout(panelDonLayout);
        panelDonLayout.setHorizontalGroup(
            panelDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDonLayout.createSequentialGroup()
                .addGroup(panelDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDonLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)
                        .addGap(274, 274, 274)
                        .addComponent(tf_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDonLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tabbedPaneCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, 882, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
        panelDonLayout.setVerticalGroup(
            panelDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbedPaneCustom1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(panelDon, "card2");

        tbl_cnkh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã CNKH", "Giấy tờ tùy thân vợ", "Họ tên vợ", "Ngày sinh vợ", "Dân tộc vợ", "Quốc tịch vợ", "Nơi trú vợ", "Giấy tờ tùy thân chồng", "Họ tên chồng", "Ngày sinh chồng", "Dân tộc chồng", "Quốc tịch chồng", "Nơi cư trú chồng", "Ngày đăng kí kết hôn", "Nơi đăng ký kết hôn"
            }
        ));
        tbl_cnkh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_cnkhMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_cnkh);

        btn_backFromGCNKHToDon.setBackground(new java.awt.Color(255, 0, 0));
        btn_backFromGCNKHToDon.setForeground(new java.awt.Color(255, 255, 255));
        btn_backFromGCNKHToDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/previous.png"))); // NOI18N
        btn_backFromGCNKHToDon.setText("Back");
        btn_backFromGCNKHToDon.setBorderColor(new java.awt.Color(255, 0, 0));
        btn_backFromGCNKHToDon.setHideActionText(true);
        btn_backFromGCNKHToDon.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btn_backFromGCNKHToDon.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_backFromGCNKHToDon.setIconTextGap(2);
        btn_backFromGCNKHToDon.setMargin(new java.awt.Insets(2, 1, 3, 14));
        btn_backFromGCNKHToDon.setRadius(15);
        btn_backFromGCNKHToDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backFromGCNKHToDonActionPerformed(evt);
            }
        });

        tf_ngaysinhchong.setLabelText("Ngày sinh chồng");

        tf_ngaydangky.setLabelText("Ngày đăng kí kết hôn");

        tf_quoctichchong.setLabelText("Quốc tịch chồng");

        tf_noidangky.setLabelText("Nơi đăng ký kết hôn");

        tf_ngaysinhvo.setLabelText("Ngày sinh vợ");

        tf_quoctichvo.setLabelText("Quốc tịch vợ");

        tf_dantocchong.setLabelText("Dân tộc chồng");
        tf_dantocchong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_dantocchongActionPerformed(evt);
            }
        });

        jLabel2.setText("Lịch sử đơn");

        tf_giaytotuythanchong.setLabelText("Giấy tờ tùy thân của chồng");
        tf_giaytotuythanchong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_giaytotuythanchongActionPerformed(evt);
            }
        });

        tf_dantocvo.setLabelText("Dân tộc vợ");

        tf_giaytotuythanvo.setLabelText("Giấy tờ tùy thân của vợ");

        tf_noicutrucuachong.setLabelText("Nơi cư trú của chồng");

        tf_hotenchong.setLabelText("Họ tên chồng");

        tf_noicutrucuavo.setLabelText("Nơi cư trú của vợ");

        tf_hotenvo.setLabelText("Họ tên vợ");

        tf_macnkh.setLabelText("Mã CNKH");

        javax.swing.GroupLayout panelGCNKHLayout = new javax.swing.GroupLayout(panelGCNKH);
        panelGCNKH.setLayout(panelGCNKHLayout);
        panelGCNKHLayout.setHorizontalGroup(
            panelGCNKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGCNKHLayout.createSequentialGroup()
                .addGroup(panelGCNKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGCNKHLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(panelGCNKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelGCNKHLayout.createSequentialGroup()
                                .addComponent(tf_macnkh, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tf_ngaydangky, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_noidangky, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelGCNKHLayout.createSequentialGroup()
                                .addGroup(panelGCNKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_hotenchong, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGCNKHLayout.createSequentialGroup()
                                        .addComponent(tf_ngaysinhchong, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tf_quoctichchong, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelGCNKHLayout.createSequentialGroup()
                                        .addComponent(tf_giaytotuythanchong, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tf_dantocchong, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tf_noicutrucuachong, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelGCNKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_noicutrucuavo, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelGCNKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(panelGCNKHLayout.createSequentialGroup()
                                            .addComponent(tf_giaytotuythanvo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tf_dantocvo, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(tf_hotenvo, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(panelGCNKHLayout.createSequentialGroup()
                                            .addComponent(tf_ngaysinhvo, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tf_quoctichvo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(panelGCNKHLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelGCNKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(btn_backFromGCNKHToDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        panelGCNKHLayout.setVerticalGroup(
            panelGCNKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGCNKHLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btn_backFromGCNKHToDon, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(panelGCNKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_hotenchong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_hotenvo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelGCNKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_ngaysinhchong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_quoctichchong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_ngaysinhvo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_quoctichvo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelGCNKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_giaytotuythanchong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_dantocchong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_giaytotuythanvo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_dantocvo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(panelGCNKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_noicutrucuavo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_noicutrucuachong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGCNKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_macnkh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_ngaydangky, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_noidangky, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(panelGCNKH, "card3");

        tf_matamtru.setLabelText("Mã tạm trú");

        tf_hoten.setLabelText("Họ tên ");

        tf_ngaysinh.setLabelText("Ngày sinh");

        tf_cccd.setLabelText("CCCD");

        tf_noicap.setLabelText("Nơi cấp CCCD");

        tf_ngaycap.setLabelText("Ngày cấp");

        tf_ngayden.setLabelText("Ngày đến");

        tf_ngaydi.setLabelText("Ngày đi");

        tf_ngaydangkyTT.setLabelText("Ngày đăng ký");

        tf_lydo.setLabelText("Lý do");

        tf_noidangkyTT.setLabelText("Nơi đăng ký");

        jLabel3.setText("Lịch sử đơn");

        tbl_tamtru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã tạm trú", "Ngày đăng ký", "Nơi đăng ký", "Họ tên", "Ngày sinh", "CCCD", "Nơi cấp CCCD", "Ngày cấp CCCD", "Ngày đến", "Ngày đi", "Ngày đăng ký"
            }
        ));
        tbl_tamtru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_tamtruMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_tamtru);

        btn_backFromTTToDon.setText("myButton1");
        btn_backFromTTToDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backFromTTToDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTTLayout = new javax.swing.GroupLayout(panelTT);
        panelTT.setLayout(panelTTLayout);
        panelTTLayout.setHorizontalGroup(
            panelTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTTLayout.createSequentialGroup()
                .addGroup(panelTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTTLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(panelTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tf_lydo, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_cccd, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                    .addComponent(tf_matamtru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(tf_ngayden, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTTLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                .addComponent(tf_ngaydi, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(tf_ngaydangkyTT, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelTTLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelTTLayout.createSequentialGroup()
                                        .addGroup(panelTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tf_hoten, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                            .addComponent(tf_noicap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(35, 35, 35)
                                        .addGroup(panelTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tf_ngaysinh, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                            .addComponent(tf_ngaycap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(tf_noidangkyTT, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panelTTLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(panelTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_backFromTTToDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        panelTTLayout.setVerticalGroup(
            panelTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTTLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btn_backFromTTToDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_matamtru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_cccd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_noicap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_ngaycap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_ngayden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_ngaydi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_ngaydangkyTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_lydo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_noidangkyTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        add(panelTT, "card4");

        tf_machungtu.setLabelText("Mã chứng tử");

        tf_cccd1.setLabelText("CCCD");

        tf_hoten1.setLabelText("Họ và tên");

        tf_ngaysinh1.setLabelText("Ngày sinh");

        tf_ngaymat.setLabelText("Ngày mất");

        tf_noimat.setLabelText("Nơi mất");

        tf_lydo1.setLabelText("Lý do");

        myButton1.setText("myButton1");

        javax.swing.GroupLayout panelGCTLayout = new javax.swing.GroupLayout(panelGCT);
        panelGCT.setLayout(panelGCTLayout);
        panelGCTLayout.setHorizontalGroup(
            panelGCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGCTLayout.createSequentialGroup()
                .addGroup(panelGCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGCTLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(panelGCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelGCTLayout.createSequentialGroup()
                                .addComponent(tf_machungtu, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(tf_cccd1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(tf_hoten1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGCTLayout.createSequentialGroup()
                                .addGroup(panelGCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_ngaysinh1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_noimat, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelGCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_ngaymat, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                                    .addComponent(tf_lydo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(panelGCTLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(myButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        panelGCTLayout.setVerticalGroup(
            panelGCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGCTLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(myButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelGCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_machungtu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_cccd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_hoten1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelGCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_ngaysinh1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_ngaymat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelGCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_noimat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_lydo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(586, Short.MAX_VALUE))
        );

        add(panelGCT, "card5");

        tf_hotenks.setLabelText("Họ tên");

        tf_maks.setLabelText("Mã khai sinh");

        tf_noisinh.setLabelText("Nơi sinh");

        tf_gioitinh.setLabelText("Giới tính");

        tf_ngaysinhks.setLabelText("Ngày sinh");

        tf_quequan.setLabelText("Quê quán");

        tf_dantoc.setLabelText("Dân tộc");

        tf_quoctich.setLabelText("Quốc tịch");

        tf_cccdcha.setLabelText("CCCD Cha");

        tf_cccdme.setLabelText("CCCD Me");

        tf_ngaydangkyks.setLabelText("Ngày đăng ký");

        tf_cccdnguoikhaisinh.setLabelText("CCCD người khai sinh");

        tf_quanhe.setLabelText("Quan hệ");

        tf_noidangkyks.setLabelText("Nơi đăng ký");

        brn_backFromKSToDon.setText("myButton2");
        brn_backFromKSToDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brn_backFromKSToDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelKSLayout = new javax.swing.GroupLayout(panelKS);
        panelKS.setLayout(panelKSLayout);
        panelKSLayout.setHorizontalGroup(
            panelKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKSLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(brn_backFromKSToDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelKSLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelKSLayout.createSequentialGroup()
                        .addComponent(tf_hotenks, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tf_maks, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tf_gioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tf_noisinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelKSLayout.createSequentialGroup()
                        .addComponent(tf_ngaysinhks, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tf_quequan, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tf_dantoc, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tf_quoctich, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelKSLayout.createSequentialGroup()
                        .addGroup(panelKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_cccdcha, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_cccdnguoikhaisinh, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(panelKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_cccdme, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_quanhe, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelKSLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(tf_ngaydangkyks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelKSLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                                .addComponent(tf_noidangkyks, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(40, 40, 40))
        );
        panelKSLayout.setVerticalGroup(
            panelKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelKSLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(brn_backFromKSToDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_hotenks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_maks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_noisinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_gioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_ngaysinhks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_quequan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_dantoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_quoctich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_cccdcha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_cccdme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_ngaydangkyks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_cccdnguoikhaisinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_quanhe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_noidangkyks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(502, Short.MAX_VALUE))
        );

        add(panelKS, "card6");

        panelTV.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tf_hotentv.setLabelText("Họ tên");

        tf_matamvang.setLabelText("Mã tạm vắng");

        tf_noichuyendi.setLabelText("Nơi chuyển đi");

        tf_noichuyenden.setLabelText("Nơi chuyển đến");

        tf_ngaysinhtv.setLabelText("Ngày sinh");

        tf_noicaptv.setLabelText("Nơi cấp");

        tf_cccdtv.setLabelText("CCCD");

        tf_ngaydangkytv.setLabelText("Ngày đăng ký");

        tf_ngayditv.setLabelText("Ngày đi");

        tf_ngayve.setLabelText("Ngày về");

        tf_lydotv.setLabelText("Lý do");

        jLabel4.setText("Lịch sử đơn");

        tbl_tamvang.setBackground(new java.awt.Color(204, 204, 204));
        tbl_tamvang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbl_tamvang.setForeground(new java.awt.Color(255, 255, 51));
        tbl_tamvang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã tạm vắng", "Ngày đăng ký", "Nơi chuyển đi", "Nới chuyển đến", "Họ tên", "Ngày sinh", "CCCD", "Nơi cấp CCCD", "Ngày đi", "Ngày về", "Lí do"
            }
        ));
        tbl_tamvang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_tamvangMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_tamvang);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(tf_ngayditv, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(55, 55, 55)
                            .addComponent(tf_ngayve, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                            .addComponent(tf_lydotv, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(tf_ngaysinhtv, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(tf_noicaptv, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(tf_hotentv, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(tf_matamvang, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_noichuyendi, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                .addComponent(tf_cccdtv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(27, 27, 27)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_noichuyenden, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                .addComponent(tf_ngaydangkytv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_hotentv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_matamvang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_noichuyendi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_noichuyenden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_ngaysinhtv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_noicaptv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_cccdtv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_ngaydangkytv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_ngayditv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_ngayve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_lydotv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btn_backFromTVToDon.setBackground(new java.awt.Color(0, 0, 255));
        btn_backFromTVToDon.setForeground(new java.awt.Color(255, 255, 255));
        btn_backFromTVToDon.setText("Back");
        btn_backFromTVToDon.setBorderColor(new java.awt.Color(255, 255, 255));
        btn_backFromTVToDon.setRadius(15);
        btn_backFromTVToDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backFromTVToDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTVLayout = new javax.swing.GroupLayout(panelTV);
        panelTV.setLayout(panelTVLayout);
        panelTVLayout.setHorizontalGroup(
            panelTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTVLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 42, Short.MAX_VALUE))
            .addGroup(panelTVLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btn_backFromTVToDon, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTVLayout.setVerticalGroup(
            panelTVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_backFromTVToDon, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(panelTV, "card7");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_donkethonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_donkethonActionPerformed
        // TODO add your handling code here:
        panelDon.setVisible(false);
        panelGCNKH.setVisible(true);

        List<DonChungNhanKetHon> listDonChungNhanKetHon;
        IChungNhanKetHonService chungNhanKetHonService = new ChungNhanKetHonServiceImpl();

        listDonChungNhanKetHon = chungNhanKetHonService.findAllCNKH(search, search);
        model = (DefaultTableModel) tbl_cnkh.getModel();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        for (DonChungNhanKetHon dcnkh : listDonChungNhanKetHon) {
            model.addRow(new Object[]{dcnkh.getMaCnkh(), dcnkh.getCCCDVo(), dcnkh.getHoTenVo(), dcnkh.getNgaySinhVo(), dcnkh.getDanTocVo(), dcnkh.getQuocTichVo(), dcnkh.getNoiCuTruVo(),
                dcnkh.getCCCDChong(), dcnkh.getHoTenChong(), dcnkh.getNgaySinhChong(), dcnkh.getDanTocChong(), dcnkh.getQuocTichChong(), dcnkh.getNoiCuTruChong(), dcnkh.getNgaydk(), dcnkh.getNoidk()});
        }
    }//GEN-LAST:event_btn_donkethonActionPerformed

    private void btn_donkhaisinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_donkhaisinhActionPerformed
        // TODO add your handling code here:
        panelDon.setVisible(false);
        panelKS.setVisible(true);

        IKhaiSinhService khaiSinhService = new KhaiSinhServiceImpl();
        KhaiSinhModel khaiSinhModel = new KhaiSinhModel();
        khaiSinhModel = khaiSinhService.findByCCCD(search);

        tf_hotenks.setText(khaiSinhModel.getHoTenKS());
        tf_maks.setText(khaiSinhModel.getMaKS());
        tf_gioitinh.setText(khaiSinhModel.getGioiTinh());
        tf_ngaysinhks.setText(String.valueOf(khaiSinhModel.getNgaySinh()));
        tf_noisinh.setText(khaiSinhModel.getNoiSinh());
        tf_quoctich.setText(khaiSinhModel.getQuocTich());
        tf_dantoc.setText(khaiSinhModel.getDanToc());
        tf_quequan.setText(khaiSinhModel.getQueQuan());
        tf_cccdcha.setText(khaiSinhModel.getCha());
        tf_cccdme.setText(khaiSinhModel.getMe());
        tf_ngaydangkyks.setText(String.valueOf(khaiSinhModel.getNgayDk()));
        tf_cccdnguoikhaisinh.setText(khaiSinhModel.getNguoiKhaiSinh());
        tf_quanhe.setText(khaiSinhModel.getQuanHe());
        tf_noidangkyks.setText(khaiSinhModel.getNoiDk());

    }//GEN-LAST:event_btn_donkhaisinhActionPerformed

    private void btn_dontamtruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dontamtruActionPerformed
        // TODO add your handling code here:
        panelDon.setVisible(false);
        panelTT.setVisible(true);

        DefaultTableModel model;
        List<DonTamTru> listDonTamTru;
        ITamTruService tamTruService = new TamTruServiceImpl();

        listDonTamTru = tamTruService.findAllTT(search);
        model = (DefaultTableModel) tbl_tamtru.getModel();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
        for (DonTamTru dtt : listDonTamTru) {
            model.addRow(new Object[]{dtt.getMaTT(), dtt.getNgayDk(), dtt.getNoiDangKy(), dtt.getHoTen(), dtt.getNgaySinh(), dtt.getCCCD(),
                dtt.getNoiCap(), dtt.getNgayCap(), dtt.getNgayDen(), dtt.getNgayDi(), dtt.getLiDo()});
        }

    }//GEN-LAST:event_btn_dontamtruActionPerformed

    private void btn_dontamvangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dontamvangActionPerformed
        // TODO add your handling code here:
        panelDon.setVisible(false);
        panelTV.setVisible(true);

        List<DonTamVang> listDonTamVang;
        ITamVangService tamVangService = new TamVangServiceImpl();

        listDonTamVang = tamVangService.findAllTV(search);
        model = (DefaultTableModel) tbl_tamvang.getModel();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
        for (DonTamVang dtv : listDonTamVang) {
            model.addRow(new Object[]{dtv.getMaTV(), dtv.getNgayDangKy(), dtv.getNoiChuyenDi(), dtv.getNoiChuyenDen(), dtv.getHoTen(), dtv.getNgaySinh(),
                dtv.getCCCD(), dtv.getNoiCapCCCD(), dtv.getNgayDi(), dtv.getNgayVe(), dtv.getLyDo()});
        }
    }//GEN-LAST:event_btn_dontamvangActionPerformed

    private void btn_thongtincongdanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thongtincongdanActionPerformed
        // TODO add your handling code here:
        showForm(new TraCuuTTCD(search));
    }//GEN-LAST:event_btn_thongtincongdanActionPerformed

    private void btn_donlyhonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_donlyhonActionPerformed
        // TODO add your handling code here:
        showForm(new TraCuuLH(search));
    }//GEN-LAST:event_btn_donlyhonActionPerformed

    private void btn_giaychungtuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_giaychungtuActionPerformed
        // TODO add your handling code here:
        showForm(new TraCuuGCT(search));
    }//GEN-LAST:event_btn_giaychungtuActionPerformed

    private void btn_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemActionPerformed
        // TODO add your handling code here:
        setSearch(tf_timkiem.getText());
        getSearch();
    }//GEN-LAST:event_btn_timkiemActionPerformed

    private void tbl_cnkhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_cnkhMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tbl_cnkh.getModel();
        tf_macnkh.setText(model.getValueAt(tbl_cnkh.getSelectedRow(), 0).toString());
        tf_giaytotuythanvo.setText(model.getValueAt(tbl_cnkh.getSelectedRow(), 1).toString());
        tf_hotenvo.setText(model.getValueAt(tbl_cnkh.getSelectedRow(), 2).toString());
        tf_ngaysinhvo.setText(model.getValueAt(tbl_cnkh.getSelectedRow(), 3).toString());
        tf_dantocvo.setText(model.getValueAt(tbl_cnkh.getSelectedRow(), 4).toString());
        tf_quoctichvo.setText(model.getValueAt(tbl_cnkh.getSelectedRow(), 5).toString());
        tf_noicutrucuavo.setText(model.getValueAt(tbl_cnkh.getSelectedRow(), 6).toString());
        tf_giaytotuythanchong.setText(model.getValueAt(tbl_cnkh.getSelectedRow(), 7).toString());
        tf_hotenchong.setText(model.getValueAt(tbl_cnkh.getSelectedRow(), 8).toString());
        tf_ngaysinhchong.setText(model.getValueAt(tbl_cnkh.getSelectedRow(), 9).toString());
        tf_dantocchong.setText(model.getValueAt(tbl_cnkh.getSelectedRow(), 10).toString());
        tf_quoctichchong.setText(model.getValueAt(tbl_cnkh.getSelectedRow(), 11).toString());
        tf_noicutrucuachong.setText(model.getValueAt(tbl_cnkh.getSelectedRow(), 12).toString());
        tf_ngaydangky.setText(model.getValueAt(tbl_cnkh.getSelectedRow(), 13).toString());
        tf_noidangky.setText(model.getValueAt(tbl_cnkh.getSelectedRow(), 14).toString());
    }//GEN-LAST:event_tbl_cnkhMouseClicked

    private void btn_backFromGCNKHToDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backFromGCNKHToDonActionPerformed
        // TODO add your handling code here:
        panelGCNKH.setVisible(false);
        panelDon.setVisible(true);
    }//GEN-LAST:event_btn_backFromGCNKHToDonActionPerformed

    private void tf_giaytotuythanchongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_giaytotuythanchongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_giaytotuythanchongActionPerformed

    private void tf_dantocchongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_dantocchongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_dantocchongActionPerformed

    private void tbl_tamtruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_tamtruMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tbl_tamtru.getModel();
        tf_matamtru.setText(model.getValueAt(tbl_tamtru.getSelectedRow(), 0).toString());
        tf_ngaydangkyTT.setText(model.getValueAt(tbl_tamtru.getSelectedRow(), 1).toString());
        tf_noidangkyTT.setText(model.getValueAt(tbl_tamtru.getSelectedRow(), 2).toString());
        tf_hoten.setText(model.getValueAt(tbl_tamtru.getSelectedRow(), 3).toString());
        tf_ngaysinh.setText(model.getValueAt(tbl_tamtru.getSelectedRow(), 4).toString());
        tf_cccd.setText(model.getValueAt(tbl_tamtru.getSelectedRow(), 5).toString());
        tf_noicap.setText(model.getValueAt(tbl_tamtru.getSelectedRow(), 6).toString());
        tf_ngaycap.setText(model.getValueAt(tbl_tamtru.getSelectedRow(), 7).toString());
        tf_ngayden.setText(model.getValueAt(tbl_tamtru.getSelectedRow(), 8).toString());
        tf_ngaydi.setText(model.getValueAt(tbl_tamtru.getSelectedRow(), 9).toString());
        tf_lydo.setText(model.getValueAt(tbl_tamtru.getSelectedRow(), 10).toString());
    }//GEN-LAST:event_tbl_tamtruMouseClicked

    private void btn_backFromTTToDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backFromTTToDonActionPerformed
        // TODO add your handling code here:
        panelTT.setVisible(false);
        panelDon.setVisible(true);
    }//GEN-LAST:event_btn_backFromTTToDonActionPerformed

    private void brn_backFromKSToDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brn_backFromKSToDonActionPerformed
        // TODO add your handling code here:
        panelKS.setVisible(false);
        panelDon.setVisible(true);
    }//GEN-LAST:event_brn_backFromKSToDonActionPerformed

    private void tbl_tamvangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_tamvangMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tbl_tamvang.getModel();
        tf_matamvang.setText(model.getValueAt(tbl_tamvang.getSelectedRow(), 0).toString());
        tf_ngaydangkytv.setText(model.getValueAt(tbl_tamvang.getSelectedRow(), 1).toString());
        tf_noichuyendi.setText(model.getValueAt(tbl_tamvang.getSelectedRow(), 2).toString());
        tf_noichuyenden.setText(model.getValueAt(tbl_tamvang.getSelectedRow(), 3).toString());
        tf_hotentv.setText(model.getValueAt(tbl_tamvang.getSelectedRow(), 4).toString());
        tf_ngaysinhtv.setText(model.getValueAt(tbl_tamvang.getSelectedRow(), 5).toString());
        tf_cccdtv.setText(model.getValueAt(tbl_tamvang.getSelectedRow(), 6).toString());
        tf_noicaptv.setText(model.getValueAt(tbl_tamvang.getSelectedRow(), 7).toString());
        tf_ngayditv.setText(model.getValueAt(tbl_tamvang.getSelectedRow(), 8).toString());
        tf_ngayve.setText(model.getValueAt(tbl_tamvang.getSelectedRow(), 9).toString());
        tf_lydotv.setText(model.getValueAt(tbl_tamvang.getSelectedRow(), 10).toString());
    }//GEN-LAST:event_tbl_tamvangMouseClicked

    private void btn_backFromTVToDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backFromTVToDonActionPerformed
        // TODO add your handling code here:
        panelTV.setVisible(false);
        panelDon.setVisible(true);
    }//GEN-LAST:event_btn_backFromTVToDonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private button.MyButton brn_backFromKSToDon;
    private button.MyButton btn_backFromGCNKHToDon;
    private button.MyButton btn_backFromTTToDon;
    private button.MyButton btn_backFromTVToDon;
    private button.MyButton btn_donkethon;
    private button.MyButton btn_donkhaisinh;
    private button.MyButton btn_donlyhon;
    private button.MyButton btn_dontamtru;
    private button.MyButton btn_dontamvang;
    private button.MyButton btn_giaychungtu;
    private button.MyButton btn_thongtincongdan;
    private button.MyButton btn_timkiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private button.MyButton myButton1;
    private javax.swing.JPanel panelDon;
    private javax.swing.JPanel panelGCNKH;
    private javax.swing.JPanel panelGCT;
    private javax.swing.JPanel panelHoKhau;
    private javax.swing.JPanel panelKS;
    private javax.swing.JPanel panelTT;
    private javax.swing.JPanel panelTV;
    private javax.swing.JPanel panelThue;
    private javax.swing.JPanel panelXemDon;
    private Swing.TabbedPaneCustom tabbedPaneCustom1;
    private javax.swing.JTable tbl_cnkh;
    private javax.swing.JTable tbl_tamtru;
    private javax.swing.JTable tbl_tamvang;
    private Swing.TextField tf_cccd;
    private Swing.TextField tf_cccd1;
    private Swing.TextField tf_cccdcha;
    private Swing.TextField tf_cccdme;
    private Swing.TextField tf_cccdnguoikhaisinh;
    private Swing.TextField tf_cccdtv;
    private Swing.TextField tf_dantoc;
    private Swing.TextField tf_dantocchong;
    private Swing.TextField tf_dantocvo;
    private Swing.TextField tf_giaytotuythanchong;
    private Swing.TextField tf_giaytotuythanvo;
    private Swing.TextField tf_gioitinh;
    private Swing.TextField tf_hoten;
    private Swing.TextField tf_hoten1;
    private Swing.TextField tf_hotenchong;
    private Swing.TextField tf_hotenks;
    private Swing.TextField tf_hotentv;
    private Swing.TextField tf_hotenvo;
    private Swing.TextField tf_lydo;
    private Swing.TextField tf_lydo1;
    private Swing.TextField tf_lydotv;
    private Swing.TextField tf_machungtu;
    private Swing.TextField tf_macnkh;
    private Swing.TextField tf_maks;
    private Swing.TextField tf_matamtru;
    private Swing.TextField tf_matamvang;
    private Swing.TextField tf_ngaycap;
    private Swing.TextField tf_ngaydangky;
    private Swing.TextField tf_ngaydangkyTT;
    private Swing.TextField tf_ngaydangkyks;
    private Swing.TextField tf_ngaydangkytv;
    private Swing.TextField tf_ngayden;
    private Swing.TextField tf_ngaydi;
    private Swing.TextField tf_ngayditv;
    private Swing.TextField tf_ngaymat;
    private Swing.TextField tf_ngaysinh;
    private Swing.TextField tf_ngaysinh1;
    private Swing.TextField tf_ngaysinhchong;
    private Swing.TextField tf_ngaysinhks;
    private Swing.TextField tf_ngaysinhtv;
    private Swing.TextField tf_ngaysinhvo;
    private Swing.TextField tf_ngayve;
    private Swing.TextField tf_noicap;
    private Swing.TextField tf_noicaptv;
    private Swing.TextField tf_noichuyenden;
    private Swing.TextField tf_noichuyendi;
    private Swing.TextField tf_noicutrucuachong;
    private Swing.TextField tf_noicutrucuavo;
    private Swing.TextField tf_noidangky;
    private Swing.TextField tf_noidangkyTT;
    private Swing.TextField tf_noidangkyks;
    private Swing.TextField tf_noimat;
    private Swing.TextField tf_noisinh;
    private Swing.TextField tf_quanhe;
    private Swing.TextField tf_quequan;
    private Swing.TextField tf_quoctich;
    private Swing.TextField tf_quoctichchong;
    private Swing.TextField tf_quoctichvo;
    private Swing.TextField tf_timkiem;
    // End of variables declaration//GEN-END:variables
}
